version: "3"
services:
    web:
        build: .
        container_name: squishychat_web
        command: node ./server/index.js
        restart: always
        ports:
            - "9912:9912"
        depends_on:
            - mongo_db
        links:
            - mongo_db
        environment:
            - MONGO_URL='mongodb://mongo_db'
            - PRODUCTION=true
    mongo_db:
        image: mongo
        restart: always
        container_name: squishychat_mongo_db
        volumes:
            - /data/db:/data/db
